
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.stats import ks_2samp

# Load Data
# Generated by parallel scripts (each row is a sample from stationary dist)
# Actually, the parallel scripts flattened the data.
try:
    ssa_df = pd.read_csv('repressilator_ssa_1000_stats.csv')
    mark_df = pd.read_csv('repressilator_markovian_1000_stats.csv')
    
    ssa_vals = ssa_df['P_folded'].values
    mark_vals = mark_df['P_folded'].values
    
    print(f"SSA Mean: {np.mean(ssa_vals):.4f}, Std: {np.std(ssa_vals):.4f}")
    print(f"Mark Mean: {np.mean(mark_vals):.4f}, Std: {np.std(mark_vals):.4f}")
    
    # Plot CDFs
    plt.figure(figsize=(8, 6))
    
    # ECDF
    def ecdf(data):
        x = np.sort(data)
        y = np.arange(1, len(x)+1) / len(x)
        return x, y
        
    x_ssa, y_ssa = ecdf(ssa_vals)
    x_mark, y_mark = ecdf(mark_vals)
    
    plt.plot(x_ssa, y_ssa, label=f'SSA 1000 Reps (Mean={np.mean(ssa_vals):.1f})', linewidth=2)
    plt.plot(x_mark, y_mark, label=f'Hybrid 1000 Reps (Mean={np.mean(mark_vals):.1f})', linewidth=2, linestyle='--')
    
    ks_stat, p_val = ks_2samp(ssa_vals, mark_vals)
    plt.title(f'Ensemble Validation (1000 Replicates)\nKS={ks_stat:.3f}, p={p_val:.2e}')
    plt.xlabel('Protein Concentration / Counts')
    plt.ylabel('CDF')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.savefig('repressilator_ensemble_validation.png')
    print("Plot saved to repressilator_ensemble_validation.png")
    
except Exception as e:
    print(f"Error loading or plotting: {e}")
